Алиева Хадижат ПИ20-1. Лабораторная работа 0.1. Знакомство с numpy

---



In [ ]:
from numpy import *
print("Задание 1: Создайте матрицу таблицы умножения с использованием списков")
table = array([[1,2,3,4,5,6,7,8,9,10],[2,4,6,8,10,12,14,16,18,20],
              [3,6,9,12,15,18,21,24,27,30],[4,8,12,16,20,24,28,32,36,40],
              [5,10,15,20,25,30,35,40,45,50],[6,12,18,24,30,36,42,48,54,60],
              [7,14,21,28,35,42,49,56,63,70],[8,16,24,32,40,48,56,64,72,80],
              [9,18,27,36,45,54,63,72,81,90],[10,20,30,40,50,60,70,80,90,100]])
print(table)

Задание 1:
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
from numpy import *
print("Задание 2: Принимать как аргументы целое число N и первый элемент (вещественное число el1)," 
      "и разность (вещественное число d) и создать матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии.")
el1 = int(input())
N = int(input())
d = int(input())
matrix = diag(arange(el1, el1+d*N, d))
print(matrix)

Задание 2: Принимать как аргументы целое число N и первый элемент (вещественное число el1),и разность (вещественное число d) и создать матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии.
5
7
1
[[ 5  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  8  0  0  0]
 [ 0  0  0  0  9  0  0]
 [ 0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0 11]]


In [ ]:
from numpy import *
import matplotlib.pyplot as plt
print("Задание 3: Из данных по температуре в Стокгольме выбрать данные относящиеся к октябрю 1970 года и" 
      "записать их в бинарный и текстовый файлы oct70.bin и oct70.txt. Затем прочитайте их импортировав в тетрадь ноутбука и сравните.")
data = genfromtxt('https://raw.githubusercontent.com/jrjohansson/scientific-python-lectures/master/stockholm_td_adj.dat')
fig, ax = plt.subplots(figsize=(14,4))
x=linspace(1,32,31)
y=array([data[i,5] for i in range(data.shape[0]) if (data[i,0]==1970)*(data[i,1]==10)])
ax.plot(x,y)
ax.axis('tight')
ax.set_title('tempeatures in Stockholm')
ax.set_xlabel('day')
ax.set_ylabel('temperature (C)');
savetxt("oct70.bin", y)
savetxt("oct70.txt", y)

Задание 3: Из данных по температуре в Стокгольме выбрать данные относящиеся к октябрю 1970 года изаписать их в бинарный и текстовый файлы oct70.bin и oct70.txt. Затем прочитайте их импортировав в тетрадь ноутбука и сравните.


In [ ]:
from numpy import *
print("Задание 4: Используя срезы извлеките нечетные элементы матрицы А.")
A = array([[n+m*10 for n in range(5)] for m in range(5)])
print(A)
res = A[A%2!=0]
print(res)

Задание 4: Используя срезы извлеките нечетные элементы матрицы А.
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[ 1  3 11 13 21 23 31 33 41 43]


In [ ]:
from numpy import *
print("Задание 5: Используйте массив из задания 1 (таблицу умножения) извлеките из него при помощи маски все числа кратные 3.")
table = array([[1,2,3,4,5,6,7,8,9,10],[2,4,6,8,10,12,14,16,18,20],
              [3,6,9,12,15,18,21,24,27,30],[4,8,12,16,20,24,28,32,36,40],
              [5,10,15,20,25,30,35,40,45,50],[6,12,18,24,30,36,42,48,54,60],
              [7,14,21,28,35,42,49,56,63,70],[8,16,24,32,40,48,56,64,72,80],
              [9,18,27,36,45,54,63,72,81,90],[10,20,30,40,50,60,70,80,90,100]])
maska = table%3==0
print(table[maska])

Задание 5: Используйте массив из задания 1 (таблицу умножения) извлеките из него при помощи маски все числа кратные 3.
[ 3  6  9  6 12 18  3  6  9 12 15 18 21 24 27 30 12 24 36 15 30 45  6 12
 18 24 30 36 42 48 54 60 21 42 63 24 48 72  9 18 27 36 45 54 63 72 81 90
 30 60 90]


In [ ]:
from numpy import *
print("Задание 7: Разбить массив таблицы умножения из задания 1 на два массива содержащие четные и нечетные значения,"
      "а затем собрать его в исходное состояние используя choose()")
table = array([[1,2,3,4,5,6,7,8,9,10],[2,4,6,8,10,12,14,16,18,20],
              [3,6,9,12,15,18,21,24,27,30],[4,8,12,16,20,24,28,32,36,40],
              [5,10,15,20,25,30,35,40,45,50],[6,12,18,24,30,36,42,48,54,60],
              [7,14,21,28,35,42,49,56,63,70],[8,16,24,32,40,48,56,64,72,80],
              [9,18,27,36,45,54,63,72,81,90],[10,20,30,40,50,60,70,80,90,100]])
maska1 = table%2==0
maska2 = table%2!=0
print(table[maska1], table[maska2])
res = choose(maska2, maska1)
print(table[res])

Задание 7: Разбить массив таблицы умножения из задания 1 на два массива содержащие четные и нечетные значения,а затем собрать его в исходное состояние используя choose()
[  2   4   6   8  10   2   4   6   8  10  12  14  16  18  20   6  12  18
  24  30   4   8  12  16  20  24  28  32  36  40  10  20  30  40  50   6
  12  18  24  30  36  42  48  54  60  14  28  42  56  70   8  16  24  32
  40  48  56  64  72  80  18  36  54  72  90  10  20  30  40  50  60  70
  80  90 100] [ 1  3  5  7  9  3  9 15 21 27  5 15 25 35 45  7 21 35 49 63  9 27 45 63
 81]
[  1   2   3   4   5   6   7   8   9  10   4   8  12  16  20   3   6   9
  12  15  18  21  24  27  30   8  16  24  32  40   5  10  15  20  25  30
  35  40  45  50  12  24  36  48  60   7  14  21  28  35  42  49  56  63
  70  16  32  48  64  80   9  18  27  36  45  54  63  72  81  90  20  40
  60  80 100]


In [ ]:
from numpy import *
print("Задание 8: Даны вектора v1(0,1,2,3,4) v2(5,6,7,8,9) найти угол между ними," 
      "учитывая что косинус угла между векторами можно найти как отношения их скалярного произведения к их длинам.")
v1 = arange(0, 5)
v2 = arange(5, 10)
vctr1 = array(v1)
vctr2 = array(v2)
skal = vctr1.dot(vctr2)
mod_a = sqrt(power(0,2) + power(1,2) + power(2,2) + power(3,2) + power(4,2))
mod_b = sqrt(power(5,2) + power(6,2) + power(7,2) + power(8,2) + power(9,2))
ugol = skal/mod_a*mod_b
print(ugol)

Задание 8: Даны вектора v1(0,1,2,3,4) v2(5,6,7,8,9) найти угол между ними,учитывая что косинус угла между векторами можно найти как отношения их скалярного произведения к их длинам.
233.23807579381202


In [ ]:
from numpy import *
print("Задание 9: Создайте две матрицы размером (5,5)." 
      "Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания," 
      "другая имеет треугольную форму содержающую 5 на основной диагонали и в позициях выше ее," 
      "а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы." 
      "Если для матрицы не удается найти обратную, видимо этому мешает нулевое значение детерминанта.")
matrix1 = diag([1,2,3,4,5])
matrix2 = matrix([[5,5,5,5,5],[0,5,5,5,5],[0,0,5,5,5],[0,0,0,5,5],[0,0,0,0,5]])
print(matrix1)
print("Детерминант: ", linalg.det(matrix1))
print("Обратная матрица: ", linalg.inv(matrix1))
print(matrix2)
print("Детерминант: ", linalg.det(matrix2))
print("Обратная матрица: ", linalg.inv(matrix2))

Задание 9: Создайте две матрицы размером (5,5).Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания,другая имеет треугольную форму содержающую 5 на основной диагонали и в позициях выше ее,а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы.Если для матрицы не у дается найти обратную, видимо этому мешает нулевое значение детерминанта.
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Детерминант:  119.99999999999997
Обратная матрица:  [[1.         0.         0.         0.         0.        ]
 [0.         0.5        0.         0.         0.        ]
 [0.         0.         0.33333333 0.         0.        ]
 [0.         0.         0.         0.25       0.        ]
 [0.         0.         0.         0.         0.2       ]]
[[5 5 5 5 5]
 [0 5 5 5 5]
 [0 0 5 5 5]
 [0 0 0 5 5]
 [0 0 0 0 5]]
Детерминант:  3124.999999999999
Обратная матрица:  [[ 0.2 -0.2  0.   0.   0. ]
 [ 0.   0.2 -0.2  0.   0. ]
 [ 0.   0.   0.2 -0.2  0. ]
 [ 0.   0.   0.  